server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index dashboard.html;

    location / {
        try_files $uri $uri/ /dashboard.html;
    }

    location /models {
        proxy_pass http://backend:8000/models;
        proxy_set_header Host $host;
        add_header 'Access-Control-Allow-Origin' '*';
    }

    location /5g/ {
        proxy_pass http://backend:8000/5g/;
        proxy_set_header Host $host;
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Content-Type';
    }

    location /6g/ {
        proxy_pass http://backend:8000/6g/;
        proxy_set_header Host $host;
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Content-Type';
    }

    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        add_header 'Access-Control-Allow-Origin' '*';
    }
}
