server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index dashboard.html;

    # Serve the dashboard
    location / {
        try_files $uri $uri/ /dashboard.html;
    }

    # Proxy API calls to the backend
    location /5g/ {
        proxy_pass http://backend:8000/5g/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Content-Type';
    }

    location /6g/ {
        proxy_pass http://backend:8000/6g/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Content-Type';
    }

    location /models {
        proxy_pass http://backend:8000/models;
        proxy_set_header Host $host;
    }

  
}
